---
name: GitHub docker container deno action template

description: A template for containerized GitHub Actions with Deno

inputs:
  timestamp:
    description: Current timestamp
    required: true

author: roamingowl

outputs:
  text:
    description: Generated textual output from action

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: docker
  image: Dockerfile
  pre-entrypoint: "/action/src/pre.ts"
