name: Action tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: denoland/setup-deno@v1
          with:
            deno-version: v1.x

        - name: Check formatting
          shell: bash
          run: |
            deno fmt --check

        - name: Check linting
          shell: bash
          run: |
            deno lint

        - name: Run tests
          shell: bash
          run: |
            deno test

    real-action:
      needs:
        - tests
      runs-on: ubuntu-latest
      steps:
        - name: Run action
          uses: ./
          with:
            timestamp: 1717453929
